[window]
decorations = "None"
opacity = 1.0

[window.padding]
x = 8
y = 8

[font]
size = 14

[font.normal]
family = "UbuntuSansMonoNerdFont"
style = "Regular"

[font.bold]
family = "UbuntuSansMonoNerdFont"
style = "Bold"

[font.italic]
family = "UbuntuSansMonoNerdFont"
style = "Italic"

[font.bold_italic]
family = "UbuntuSansMonoNerdFont"
style = "Bold Italic"

[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

[colors.cursor]
text = "#1d2021"
cursor = "#ebdbb2"

[colors.selection]
text = "#1d2021"
background = "#ebdbb2"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Off" }
