# Fonts
font_size 15
bold_font        auto
italic_font      auto
bold_italic_font auto

# ---nnn---
# Allow other programs (like nnn) to control Kitty
allow_remote_control yes

# Create a socket for nnn to communicate with Kitty
listen_on unix:/tmp/kitty

# Ensure the 'splits' layout is enabled so nnn can open side-by-side panes
enabled_layouts splits

# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME
